config/routes.rb
Hvz::Application.routes.draw do
  get "check_ins" => "check_ins#index"
  get "check_ins/new", :as => "check_in_wizard"
  get "check_ins/create", :as => "check_in"
  get "feeds/create"

  match "/people/login/", to: "people#login", via: :all
  match "/people/logout/", to: "people#logout", via: :all
  resources :people, :tags, :feeds
  resources :attendances
  get "bonus_codes/claim" => "bonus_codes#claim", :as => "claim_bonus_code"
  put "bonus_codes/claim" => "bonus_codes#claim_submit", :as => "submit_bonus_code"
  resources :bonus_codes
  resources :missions, :id => /[0-9]*/ do
    collection do
      get :autocomplete_person_name
      get 'list'
    end

    member do
      get 'attendance'
      get 'feeds'
      get 'points'
      post 'points' => 'missions#save_points'
    end
  end
  resources :players, :as => :registrations, :controller => :registrations, :id=>/[0-9]*/ do
      get 'showwaiver'
    resources :infractions
  end
  match '/players/find_by_code/' => 'registrations#find_by_code', :as => 'find_registration_by_code', :via => 'get'
  get 'players/:id/waiver' => "waiver#new", :as => "sign_waiver"
  post 'players/:id/waiver' => "waiver#create", :as => "waivers"

  resources :games do
    collection do
      post 'update_current'
    end

    member do
      get 'tools'
      get 'rules'
      get 'tree'
      get 'heatmap'
      get 'emails'
      get 'text'
      post 'text' => 'games#text_create'
      get 'admin_register' => 'games#admin_register_new'
      post 'admin_register' => 'games#admin_register_create'
    end
  end

  get '/contact' => 'contact_messages#new'
  resources :contact, :as => :contact_messages, :controller => :contact_messages do
    collection do
      get :list
    end
  end

  match "squads/:id", to: "squad#show", as: "squad", via: :all
  match "squads", to: "squad#index", as: "squads", via: :all
  match "players/:id/joinsquad/:squadid", to: "registrations#joinsquad", as: "join_squad", via: :all

  root :to => "index#root"

end

app/views/index/_countdown.html.haml
- if @current_game.ongoing?
  - time = @current_game.game_ends
  - desc = 'left to survive'
- else
  - time = @current_game.game_begins
  - desc = 'until the game begins!'

- content_for :javascripts do
  :javascript
    $(function() {
      $('#countdown').countdown({until: new Date(Date.UTC(#{time.utc.strftime("%Y, %m - 1, %d, %H, %M, %S")})), description: "#{j desc}"})
    });
#countdown

app/views/index/_userloggedin.html.haml
%li.dropdown
  = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
    = person.name
    %b.caret
  %ul.dropdown-menu
    %li= link_to 'Edit Info', edit_person_path(person)
    - if person.is_playing_current_game?
      - r = person.current_game_registration
      - if r.is_off_campus
        %li= link_to 'Off-Campus Check In', check_in_path
    %li= link_to "Logout", people_logout_url()

app/views/index/root.html.haml
%div.span-16.gameinfo
  %h2.dink Game Information
  =RedCloth.new(@current_game.information).to_html.html_safe
%div.span-5.last.quickstats
  - unless @current_game.id.nil?
    %h2.dink Game Status
    %table
      = render 'games/gamestats', game: @current_game
  %h2.dink 
    Recent Updates
  %ul
  - @items[0,5].each do |i|
    - if i.is_a?(Tag)
      %li= tag_text(i)
    - if i.is_a?(CheckIn)
      %li= checkin_text(i)
  %h2.dink 
    Sponsors
  =image_tag 'bgc_logo_small.png', :width=>'125'
  =image_tag "USGlogo.jpg", :width=>"100"