config/routes.rb
Hvz::Application.routes.draw do
  get "check_ins" => "check_ins#index"
  get "check_ins/new", :as => "check_in_wizard"
  get "check_ins/create", :as => "check_in"
  get "feeds/create"

  match "/people/login/", to: "people#login", via: :all
  match "/people/logout/", to: "people#logout", via: :all
  resources :people, :tags, :feeds
  resources :attendances
  get "bonus_codes/claim" => "bonus_codes#claim", :as => "claim_bonus_code"
  put "bonus_codes/claim" => "bonus_codes#claim_submit", :as => "submit_bonus_code"
  resources :bonus_codes
  resources :missions, :id => /[0-9]*/ do
    collection do
      get :autocomplete_person_name
      get 'list'
    end

    member do
      get 'attendance'
      get 'feeds'
      get 'points'
      post 'points' => 'missions#save_points'
    end
  end
  resources :players, :as => :registrations, :controller => :registrations, :id=>/[0-9]*/ do
      get 'showwaiver'
    resources :infractions
  end
  match '/players/find_by_code/' => 'registrations#find_by_code', :as => 'find_registration_by_code', :via => 'get'
  get 'players/:id/waiver' => "waiver#new", :as => "sign_waiver"
  post 'players/:id/waiver' => "waiver#create", :as => "waivers"

  resources :games do
    collection do
      post 'update_current'
    end

    member do
      get 'tools'
      get 'rules'
      get 'tree'
      get 'heatmap'
      get 'emails'
      get 'text'
      post 'text' => 'games#text_create'
      get 'admin_register' => 'games#admin_register_new'
      post 'admin_register' => 'games#admin_register_create'
    end
  end

  get '/contact' => 'contact_messages#new'
  resources :contact, :as => :contact_messages, :controller => :contact_messages do
    collection do
      get :list
    end
  end

  match "squads/:id", to: "squad#show", as: "squad", via: :all
  match "squads", to: "squad#index", as: "squads", via: :all
  match "players/:id/joinsquad/:squadid", to: "registrations#joinsquad", as: "join_squad", via: :all

  root :to => "index#root"

end

app/models/waiver.rb
class Waiver < ActiveRecord::Base
  belongs_to :game
  belongs_to :person

  attr_accessor :signature

  validate :check_signature
  validates_presence_of :emergencyname, :emergencyphone, :studentid

private

  def check_signature
    return unless new_record?

    return if signature.try(:downcase) == person.name.downcase

    errors.add(:signature, 'must match your name as it appears at the top')
  end
end

app/controllers/waiver_controller.rb
class WaiverController < ApplicationController
  before_filter :check_login
  before_filter :require_can_register

  def new
    @waiver = Waiver.new.tap do |w|
      w.person = @logged_in_person

      if last_waiver = @logged_in_person.waivers.last
        w.studentid = last_waiver.studentid
      end
    end
  end

  def create
    @logged_in_person.update_attributes(params[:person])

    if !@logged_in_person.legal_to_sign_waiver?
      return redirect_to new_registration_url
    end

    @w = Waiver.where(person_id: @logged_in_person, game_id: @current_game).
      first_or_initialize(params[:waiver])

    unless @logged_in_person.legal_to_sign_waiver?
      return render :under18
    end

    if !@w.valid?
      flash[:error] = @w.errors.full_messages.first
    end

    if %w[chk1 chk2 chk3 chk4].any? { |n| params[:confirmation][n] == '0' }
      flash[:error] = 'Error: You must check all boxes to accept the waiver.'
    end

    return redirect_to sign_waiver_path(next: params[:next]) if flash[:error]

    if @w.save
      case params[:next]
      when 'registration'
        redirect_to new_registration_path
      else
        redirect_to sign_waiver_path
      end
    end
  end
end

app/helpers/waiver_helper.rb
module WaiverHelper
end

app/views/waiver/new.html.haml
%h2.dink
  = @current_game.short_name + " Registration (Step 2 of 3)"
%div.registration
  = form_for(@waiver, url: waivers_path(@logged_in_person, next: params[:next])) do |f|
    %div.span-10
      %table
        %tr
          %td
            Name:
          %td
            =text_field_tag nil, @logged_in_person.name, {:disabled => true, :size=>15}
        = fields_for :person do |g|
          %tr
            %td{ style: 'width: 75px' }
              = g.label :date_of_birth, 'Date Of Birth:'
            %td
              = g.date_select :date_of_birth, order: [:month, :day, :year],
                start_year: 1940, end_year: Time.now.year-14
    %div.span-1
    %div.span-10
      =f.label :studentid, "Student ID:"
      =f.text_field :studentid
    %div.span-22.last.clear
      I,
      %b=@logged_in_person.name
      am participating in the Big Games Club's Humans vs Zombies game on Friday, March 24 – Friday, March 31, 2017 all day. My participation may include some risks. I am aware of the risks that may be encountered during this program and I understand that the risks may include personal injury and damage to property.
      %br
      I have been informed of risks that may be encountered during this program and if I have any questions about the activity's content, nature, risks or hazards, I have contacted the activity's coordinator and have discussed those questions to my satisfaction. I understand that my participation in this activity does not require travel but consists of game play on Case Western Reserve University’s campus and may involve exposure to risk of personal injury or damage to property.

      As a condition of participating in this activity, I agree to the following:
      = fields_for :confirmation do |g|
        %table
          %tr
            %td{:style=>"background-color:#58FF3A"}=g.check_box :chk1
            %td
              1. I am physically capable of participating in this activity. I understand that I am responsible for any health and accident insurance which I may deem necessary.
          %tr
            %td{:style=>"background-color:#58FF3A"}=g.check_box :chk2
            %td
              2. I agree to abide by all rules and regulations set forth by the facilitators of the Humans vs. Zombies game. Failure to follow these rules may result in my immediate dismissal from the game.
          %tr
            %td{:style=>"background-color:#58FF3A"}=g.check_box :chk3
            %td
              3. In consideration of being granted the opportunity to participate in this activity and use services and facilities furnished or made available by Case Western Reserve University as well as the assistance and advice of employees of the University, I hereby release and forever discharge Case Western Reserve University, the Office of Student Activities and Leadership; the Undergraduate Student Government, the Big Games Club and its trustees, officers, employees, and agents from all legal claims for injuries, damages, or losses of any kind, which may arise out of my participation in this program, other than those claims directly attributable to the grossly negligent acts or omissions of Case Western Reserve University, or its trustees, officers or employees.
          %tr
            %td{:style=>"background-color:#58FF3A"}=g.check_box :chk4
            %td
              4. I agree to comply with all regulations, rules and policies of Case Western Reserve University while participating in this activity. I fully acknowledge that I am responsible for following all policies and procedures as set forth by the 2016- 2017 Student Services Guide. I understand that I am responsible for any medical or other personal insurance that I may deem necessary. I also understand that Case Western Reserve University is not responsible for my safety under any circumstances.

      I certify that I have fully read this release and that I understand its terms and conditions and agree to be bound by them. I certify that I am over the age of eighteen and have executed this agreement of my own free will. I certify that
      I have read #{link_to 'the full and complete rules', rules_game_path(Game.current)}.
      %div.span-13
        =f.label :signature, "Signature (type your name as it reads above):"
        =f.text_field :signature
      %div.span-8
        =f.label :datesigned, "Date Signed:"
        =f.date_select :datesigned
      %div.span-12
        %table
          %thead
            %th{:colspan=>"2"} Emergency Contact Information:
          %tbody
            %tr
              %td=f.label :emergencyname, "Emergency Contact:"
              %td=f.text_field :emergencyname
            %tr
              %td=f.label :emergencyrelationship, "Relationship:"
              %td=f.text_field :emergencyrelationship
            %tr
              %td=f.label :emergencyphone, "Phone Number:"
              %td=f.text_field :emergencyphone
    %div.span-22
      =f.submit "Onwards! (Continue Registration Process)",
        confirm: "Have you actually read the full rules? Please also show up to one of the rules meetings. Wednesday 3/22 or Thursday 3/23 in Schmitt!"