config/routes.rb
Hvz::Application.routes.draw do
  get "check_ins" => "check_ins#index"
  get "check_ins/new", :as => "check_in_wizard"
  get "check_ins/create", :as => "check_in"
  get "feeds/create"

  match "/people/login/", to: "people#login", via: :all
  match "/people/logout/", to: "people#logout", via: :all
  resources :people, :tags, :feeds
  resources :attendances
  get "bonus_codes/claim" => "bonus_codes#claim", :as => "claim_bonus_code"
  put "bonus_codes/claim" => "bonus_codes#claim_submit", :as => "submit_bonus_code"
  resources :bonus_codes
  resources :missions, :id => /[0-9]*/ do
    collection do
      get :autocomplete_person_name
      get 'list'
    end

    member do
      get 'attendance'
      get 'feeds'
      get 'points'
      post 'points' => 'missions#save_points'
    end
  end
  resources :players, :as => :registrations, :controller => :registrations, :id=>/[0-9]*/ do
      get 'showwaiver'
    resources :infractions
  end
  match '/players/find_by_code/' => 'registrations#find_by_code', :as => 'find_registration_by_code', :via => 'get'
  get 'players/:id/waiver' => "waiver#new", :as => "sign_waiver"
  post 'players/:id/waiver' => "waiver#create", :as => "waivers"

  resources :games do
    collection do
      post 'update_current'
    end

    member do
      get 'tools'
      get 'rules'
      get 'tree'
      get 'heatmap'
      get 'emails'
      get 'text'
      post 'text' => 'games#text_create'
      get 'admin_register' => 'games#admin_register_new'
      post 'admin_register' => 'games#admin_register_create'
    end
  end

  get '/contact' => 'contact_messages#new'
  resources :contact, :as => :contact_messages, :controller => :contact_messages do
    collection do
      get :list
    end
  end

  match "squads/:id", to: "squad#show", as: "squad", via: :all
  match "squads", to: "squad#index", as: "squads", via: :all
  match "players/:id/joinsquad/:squadid", to: "registrations#joinsquad", as: "join_squad", via: :all

  root :to => "index#root"

end

app/models/bonus_code.rb
class BonusCode < ActiveRecord::Base
  belongs_to :registration
  belongs_to :game

  validates_uniqueness_of :code, :scope => [:game_id]

  attr_accessor :person_name, :person_id

  def person_name
    unless self.registration.nil?
      return self.registration.person.name
    end
  end
end

app/controllers/bonus_codes_controller.rb
class BonusCodesController < ApplicationController
  before_filter :check_is_registered, :only => [:claim, :claim_submit]
  before_filter :check_admin, :only => [:new, :edit, :update, :create, :destroy]
  def new
    @code = BonusCode.new(params[:bonus_code])
  end

  def update
    @code = BonusCode.find(params[:id])
    if @code.nil?
      flash[:error] = "Could not find Bonus Code ID"
    else
      @registration = Registration.find_by_game_id_and_person_id(@current_game.id, params[:bonus_code][:person_id])
      if @registration.nil?
        flash[:error] = "Error: That person is not playing this game."
        redirect_to edit_bonus_code_url(@code)
        return
      end
      @code.attributes = params[:bonus_code]
      @code.registration = @registration
      @code.save()
    end
    redirect_to bonus_codes_url()
  end

  def create
    @code = BonusCode.new(params[:bonus_code])
    @code.code = @code.code.upcase
    @code.game = @current_game
    if @code.save()
      redirect_to bonus_codes_url()
      return
    else
      flash[:error] = @code.errors.full_messages.first
      render :new
    end
  end

  def index
    @codes = @current_game.bonus_codes
    if !@is_admin
      @codes = @codes.each{|x| x.registration_id.nil? and x.code = "??????"}.sort{|x,y| x.points <=> y.points}
    end
  end

  def show
  end

  def edit
    @code = BonusCode.find(params[:id])
    if @code.nil?
      flash[:error] = "Could not find Bonus Code ID"
      redirect_to bonus_codes_url()
    end
  end

  def destroy
    @code = BonusCode.find(params[:id])
    if @code.nil?
      flash[:error] = "Could not find Bonus Code ID"
    else
      @code.delete()
    end
    redirect_to bonus_codes_url()
  end

  def claim

  end

  def claim_submit
    if @is_admin
      @registration = Registration.find_by_game_id_and_person_id(@current_game.id, params[:person_id])
    else
      @registration = @logged_in_registration
    end
    if @registration.nil?
      flash[:error] = "Invalid Person For Current Game."
      redirect_to claim_bonus_code_url()
      return
    end
    @bonus_code = BonusCode.find_by_game_id_and_code(@current_game.id, params[:code_bonus].upcase)
    if @bonus_code.nil?
      flash[:error] = "Invalid Code!"
      redirect_to claim_bonus_code_url()
      return
    end
    # Valid code! Update and save.
    if @bonus_code.registration.nil?
      # Never before used code
      @bonus_code.registration = @registration
      if not @bonus_code.save()
        flash[:error] = "There was a problem registering this code. Please report this."
        redirect_to claim_bonus_code_url()
        return
      end
    else
      flash[:error] = "This code has already been used!"
      redirect_to claim_bonus_code_url()
      return
    end
    redirect_to bonus_codes_url()
  end

end

app/helpers/bonus_codes_helper.rb
module BonusCodesHelper
end

app/views/bonus_codes/claim.html.haml
%h2.dink Bonus Code Input
Hidden around campus are various bonus codes. Input the code into this box and you will be rewarded points for finding it.

= form_tag(submit_bonus_code_url(), :method => :put)
%div.span-5
  :plain
    &nbsp;
%div.span-12
  %table
    %tbody
      %tr
        %td=label_tag(:code_bonus, "Bonus Code:")
        %td=text_field_tag(:code_bonus)
      - if @is_admin
        %th.admin{:colspan=>2}
          Admin Options:
        %tr
          %td.admin
            %b Person:
          %td
            person here
      %tr
        %td{:colspan=>2,:style=>"text-align:center"}=submit_tag("Claim the Code!")

app/views/bonus_codes/create.html.haml
<h1>BonusCodes#create</h1>
<p>Find me in app/views/bonus_codes/create.html.erb</p>

app/views/bonus_codes/edit.html.haml
%h2.dink Edit Bonus Code:
%div.span-5
  :plain
    &nbsp;
%div.span-12
  = form_for(@code) do |f|
    %table
      %tbody
        %tr
          %td.admin= f.label :code, "Code:"
          %td= f.text_field :code
        %tr
          %td.admin= f.label :points, "Points:"
          %td= f.text_field :points
        %tr
          %td.admin= f.label :person_name, "Claimed By:"
          %td
            = f.hidden_field :person_id
            = f.autocomplete_field :person_name, autocomplete_person_name_missions_path, :id_element => "#bonus_code_person_id"
        %tr
          %td{:colspan=>2, :style=>"text-align:center"}=f.submit "Update Bonus Code"

app/views/bonus_codes/index.html.haml
Bonus Codes can be found at various points on campus.
%br
=link_to "Enter Bonus Code", claim_bonus_code_url()
%table
  %thead
    -if @is_admin
      %th.admin
        %b Code
    - else
      %th
        %b Code
    %th
      %b Point Value
    %th
      %b Claimed?
    - if @is_admin
      %th.admin
        %b Edit
      %th.admin
        %b Delete
  %tbody
    - @codes.each do |c|
      %tr
        %td=c.code
        %td=c.points
        - if c.registration.nil?
          %td="No"
        - else
          %td=c.registration.person.name
        - if @is_admin
          %td.admin=link_to "Edit", edit_bonus_code_url(c)
          %td.admin=link_to "Delete", bonus_code_url(c), {:method=>:delete, :confirm=>"Are you sure you wish to delete this code?!"}
-if @is_admin
  =link_to "Create New Code", new_bonus_code_url(), {:class=>"admin"}

app/views/bonus_codes/list.html.haml
<h1>BonusCodes#list</h1>
<p>Find me in app/views/bonus_codes/list.html.erb</p>

app/views/bonus_codes/new.html.haml
%h2.dink Create New Bonus Code:
%div.span-5
  :plain
    &nbsp;
%div.span-12
  = form_for(@code) do |f|
    %table
      %tbody
        %tr
          %td.admin= f.label :code, "Code:"
          %td= f.text_field :code
        %tr
          %td.admin= f.label :points, "Points:"
          %td= f.text_field :points
        %tr
          %td{:colspan=>2, :style=>"text-align:center"}=f.submit "Create Bonus Code"

app/views/bonus_codes/show.html.haml
<h1>BonusCodes#show</h1>
<p>Find me in app/views/bonus_codes/show.html.erb</p>