config/routes.rb
Hvz::Application.routes.draw do
  get "check_ins" => "check_ins#index"
  get "check_ins/new", :as => "check_in_wizard"
  get "check_ins/create", :as => "check_in"
  get "feeds/create"

  match "/people/login/", to: "people#login", via: :all
  match "/people/logout/", to: "people#logout", via: :all
  resources :people, :tags, :feeds
  resources :attendances
  get "bonus_codes/claim" => "bonus_codes#claim", :as => "claim_bonus_code"
  put "bonus_codes/claim" => "bonus_codes#claim_submit", :as => "submit_bonus_code"
  resources :bonus_codes
  resources :missions, :id => /[0-9]*/ do
    collection do
      get :autocomplete_person_name
      get 'list'
    end

    member do
      get 'attendance'
      get 'feeds'
      get 'points'
      post 'points' => 'missions#save_points'
    end
  end
  resources :players, :as => :registrations, :controller => :registrations, :id=>/[0-9]*/ do
      get 'showwaiver'
    resources :infractions
  end
  match '/players/find_by_code/' => 'registrations#find_by_code', :as => 'find_registration_by_code', :via => 'get'
  get 'players/:id/waiver' => "waiver#new", :as => "sign_waiver"
  post 'players/:id/waiver' => "waiver#create", :as => "waivers"

  resources :games do
    collection do
      post 'update_current'
    end

    member do
      get 'tools'
      get 'rules'
      get 'tree'
      get 'heatmap'
      get 'emails'
      get 'text'
      post 'text' => 'games#text_create'
      get 'admin_register' => 'games#admin_register_new'
      post 'admin_register' => 'games#admin_register_create'
    end
  end

  get '/contact' => 'contact_messages#new'
  resources :contact, :as => :contact_messages, :controller => :contact_messages do
    collection do
      get :list
    end
  end

  match "squads/:id", to: "squad#show", as: "squad", via: :all
  match "squads", to: "squad#index", as: "squads", via: :all
  match "players/:id/joinsquad/:squadid", to: "registrations#joinsquad", as: "join_squad", via: :all

  root :to => "index#root"

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :game
  has_many :attendances
  has_many :feeds

  validates_presence_of :game_id, :title

  def validate
    if self.start < self.game.game_begins or self.end > self.game.game_ends
      self.errors.add_to_base("Mission's times are not between the game's begin and end times!")
    end
  end

  def times
    ftime = "%A, %B %e, %Y @ %I:%M %p"
    times = {
      :start => self.start.strftime(ftime),
      :end => self.end.strftime(ftime)
    }
  end

  def player_attending?(registration)
    @registration_ids ||= Set.new(attendances.pluck(:registration_id))

    @registration_ids.include?(registration.id)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_filter :check_admin, :except => [ :show, :index ]
  autocomplete :person, :name

  def new
    @mission = Mission.new
  end

  def attendance
    @mission = Mission.find(params[:id], include: { game: { registrations: :person } })
    @game = @mission.game
  end

  def feeds
    @mission = Mission.find(params[:id], :include => [:feeds, {:attendances => :registration}])
    @feeds = @mission.feeds.includes(:registration => :person).sort_by(&:created_at).reverse
    @all_zombies = Set.new(Registration.where(:game_id => @current_game.id).
      includes(:game, :taggedby, :tagged, :feeds, :attendances, :person).
      select{ |x| x.is_zombie? || x.is_recently_deceased? })
    @present_zombies = @all_zombies & Set.new(@mission.attendances.map(&:registration))
    @need_feeding = (@all_zombies - Set.new(@feeds.map(&:registration))).
      sort_by{|x| [@present_zombies.include?(x) ? 0 : 1, (x.tagged.present? || x.attendances.present?) ? 0 : 1,
                   x.state_history[:deceased], -x.score]}

    @feed = Feed.new({:mission => @mission})
  end

  def create
    @mission = Mission.new(params[:mission])
    @mission.game = @current_game
    if @mission.save
      redirect_to list_missions_path
    else
      flash[:error] = @mission.errors.full_messages.first
      redirect_to new_mission_path
    end
  end

  def index
    @missions = @current_game.missions.order(:start)
  end

  def show
    @mission = Mission.find(params[:id])
  end

  def list
    @missions = @current_game.missions.sort_by(&:start)
  end

  def edit
  @mission = Mission.find(params[:id])
  end

  def update
  @mission = Mission.find(params[:id])
  if @mission.update_attributes(params[:mission])
    redirect_to missions_url()
  else
    flash[:error] = "Could not save mission!"
    redirect_to root_url()
  end
  end

  def points
    @mission = Mission.find(params[:id], :include => {
      :attendances => { :registration => [:person, :game, :taggedby, :tagged, :feeds]}
    })
    @player_factions = Hash.new([]).merge(
      @mission.attendances.group_by { |a| a.registration.state_at(@mission.start) }
    )
  end

  def save_points
    @mission = Mission.find(params[:id], :include => {
      :attendances => { :registration => [:person, :game, :taggedby, :tagged, :feeds]}
    })

    @player_factions = Hash.new([]).merge(
      @mission.attendances.group_by { |a| a.registration.state_at(@mission.start) }
    )

    # If this is a mass assignment:
    if params[:mass_points].present?
      [ :human, :zombie, :deceased ].each do |faction|
        Attendance.
          where(:id => @player_factions[faction].map(&:id)).
          update_all(:score => params[:mass_points][faction].to_i)
      end
      return redirect_to points_mission_url(@mission)
    end

    # If this is an individual assignment:
    if params[:points].present?
      params[:points].each do |id, points|
        next if points.empty?
        Attendance.find(id).update_attribute(:score, points)
      end
      return redirect_to points_mission_url(@mission)
    end
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_missionfeeds.html.haml
%h2.dink Current Feeds (#{@feeds.length}):
%table
  - @feeds.each do |f|
    - if f.registration
      %tr
        %td=f.registration.person.name

app/views/missions/attendance.html.haml
- content_for :javascripts do
  = javascript_include_tag "backbone/models/player"
  = javascript_include_tag "backbone/collections/playerList"
  = javascript_include_tag "backbone/views/attendingPlayers"
  = javascript_include_tag "backbone/views/playerAutocomplete"
  
  :javascript
    $(function() {
      var players = #{render 'shared/player_list', game: @game, mission: @mission},
          attendingPlayers = new HvZ.AttendingPlayers({
            players: players,
            missionId: #{@mission.id},
          });
    });
:css
  #playerList > .autocomplete-container {
    margin: auto;
  }
%h2.dink Add New Attendee:
#playerList
%script{type: "text/template", id: "playersTemplate"}
  Humans:
  %b <%= humans.length %>
  | Zombies:
  %b <%= zombies.length %>
  | Deceased:
  %b <%= deceased.length %>
  %br
  %br
  %ol
    <% _.each(players, function(p) { %>
    %li <%= p.get('name') %> [ <a href='#' class='delete-attendance' data-attendance=<%= p.get('attendance') %>>x</a> ]
    <% }); %>


%h2.dink Current Mission Attendees:
#attendingPlayers

app/views/missions/create.html.haml
<h1>Missions#create</h1>
<p>Find me in app/views/missions/create.html.erb</p>

app/views/missions/edit.html.haml
%table
  %thead
    %th{:colspan=>2} Edit Mission!
  %tbody
    =form_for(@mission) do |f|
      %tr
        %td
          %b=f.label :title, "Title:"
        %td=f.text_field :title
      %tr
        %td 
          %b=f.label :start, "Mission Start Time:"
        %td=f.datetime_select :start
      %tr
        %td
          %b=f.label :end, "Mission End Time:"
        %td=f.datetime_select :end
      %tr
        %td 
          %b
            =f.label :storyline, "Storyline"
            (uses
            %a{:href=>"http://www.textism.com/tools/textile/"} textile
            )
        %td=f.text_area :storyline
      %tr
        %td
          %b 
            =f.label :description, "Mission Description"
            (uses
            %a{:href=>"http://www.textism.com/tools/textile/"} textile
            )
        %td=f.text_area :description
      %tr
        %td{:colspan=>2}=f.submit

app/views/missions/feeds.html.haml
%h2.dink Mission Feeds
Note, although mission feeds in the real game are caused by a specific zombie, these feeds will not be attributed to a zombie and
are not counted towards any kill totals or point calculations.
=form_for(@feed,:remote=>:true, :update=>"feeds") do |f|
  %table
    %tbody
      %tr
        %td Player Name:
        %td
          =f.hidden_field :person_id
          =f.autocomplete_field :person_name, autocomplete_person_name_missions_path, :id_element=>"#feed_person_id"
          =f.hidden_field :mission_id, :value => @feed.mission.id
      %tr
        %td Feed Time:
        %td
          %b
            =@feed.mission.end.strftime("%A @ %I:%M %p")
          (to change this time, change the
          =link_to("mission end time",edit_mission_url(@feed.mission))+")"
      %tr
        %td Mass Feeds?
        %td
          .admin=link_to "Feed The Whole Horde", feeds_create_url(:mass_feed => 'true', :mission_id => @feed.mission_id), :confirm => "Are you sure you wish to feed the whole horde?"
.span-10#feeds
  =render :partial => "missionfeeds"
.span-10#need_feeding
  %h2.dink Need To Be Fed:
  - @need_feeding.each do |r|
    - if @present_zombies.include?(r)
      %b= r.person.name
    - else
      = r.person.name
    (#{(r.time_until_death/1.hour).ceil} hours, #{r.attendances.length} missions, #{r.tagged.length} tags, #{r.score} points)
    %br

app/views/missions/index.html.haml
%h2.dink 
  Missions - 
  =@current_game.short_name
%ol.missionlist
  -@missions.each do |m|
    %li.dink=link_to(m.title + " (" + date_humanize_dayofweek_and_time(m.start) + ")",mission_url(m))

app/views/missions/list.html.haml
%table
  %thead
    %th Mission Title
    %th Start Time
    %th Edit Link
    %th Delete Link
    %th Attendance
    %th Feeds
    %th Points
  %tbody
    - @missions.each do |m|
      %tr
        %td=m.title
        %td=m.times[:start]
        %td=link_to("Edit", edit_mission_url(m))
        %td=link_to("Delete", mission_url(m), :method=>:delete)
        %td=link_to("Attendance", attendance_mission_url(m))
        %td=link_to("Feeds", feeds_mission_url(m))
        %td=link_to("Points", points_mission_url(m))
=link_to "Add New Mission", new_mission_url()

app/views/missions/new.html.haml
%table
  %thead
    %th{:colspan=>2} New Mission!
  %tbody
    =form_for(@mission) do |f|
      %tr
        %td
          %b=f.label :title, "Title:"
        %td=f.text_field :title
      %tr
        %td 
          %b=f.label :start, "Mission Start Time:"
        %td=f.datetime_select :start
      %tr
        %td
          %b=f.label :end, "Mission End Time:"
        %td=f.datetime_select :end
      %tr
        %td 
          %b
            =f.label :storyline, "Storyline"
            (uses
            %a{:href=>"http://www.textism.com/tools/textile/"} textile
            )
        %td=f.text_area :storyline
      %tr
        %td
          %b 
            =f.label :description, "Mission Description"
            (uses
            %a{:href=>"http://www.textism.com/tools/textile/"} textile
            )
        %td=f.text_area :description
      %tr
        %td{:colspan=>2}=f.submit

app/views/missions/points.html.haml
%h2.dink Points

%h3.dink Mass Point Assignment
=form_for(points_mission_url, :method => :post) do |f|
  %table
    %thead
      %th Faction At Mission Begin
      %th Number of Players
      %th Points
    %tbody
      %tr
        %td Human
        %td= @player_factions[:human].length
        %td= text_field_tag 'mass_points[human]', nil
      %tr
        %td Zombie
        %td= @player_factions[:zombie].length
        %td= text_field_tag 'mass_points[zombie]', nil
      %tr
        %td Deceased
        %td= @player_factions[:deceased].length
        %td= text_field_tag 'mass_points[deceased]', nil
  =f.submit "Mass Assign Points", :confirm => 'Are you sure you wish to mass assign points? This will eliminate any individual point assignments!'

%br
%br
%h3.dink Individual Point Assignment
=form_for(points_mission_url, :method => :post) do |f|
  %table
    %thead
      %th Player
      %th Faction At Mission Begin
      %th Points
    %tbody
      - @mission.attendances.each do |a|
        %tr
          %td= a.registration.person.name
          %td= a.registration.state_at(@mission.start).capitalize
          %td= text_field_tag "points[#{a.id}]", a.score
  =f.submit "Save Scores"

app/views/missions/show.html.haml
%h2.dink=@mission.title
%table.span-14
  %tr
    %td
      Begins:
    %td
      =date_humanize(@mission.start)
  %tr
    %td
      Ends (approximate):
    %td
      =date_humanize(@mission.end)
%h3.dink
  Storyline:
%div{:align=>"left"}
  =RedCloth.new(@mission.storyline).to_html.html_safe
%h3.dink
  Mission Details:
%div{:align=>"left"}
  =RedCloth.new(@mission.description).to_html.html_safe